### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by arichtman** [tiann/AnyLauncher#3]
How do you use this?

I can install the APK fine but nothing shows up, and if I select system gestures it still tells me it won't work with 3rd part launcher.
If I enable gestures and afterwards switch the default launcher off Xiaomi it reverts the navigation.

Poco F4 GT model # 21121210G
HyperOS 1.0.1.ULJEUXM
Android 14 UKQ1.230917.001

**Comment by SherlockChiang** [comment]
Firstly, this is an Xposed module, and you need LSPosed or a similar adapter to activate it. Once you load this APK via LSPosed, you need to reboot in order to activate it. When you need to switch it to gesture mode, simply use your MI assistant, known as Xiao Ai Tong Xue in Chinese. You can type "全面屏手势" or "Gesture Mode" to activate it.

Mi 12S
HyperOS 1.0.24.3.25.DEV
Android 14

**Comment by arichtman** [comment]
Ahhh ok - I will try that. Thank you!
